version: "3"
services:
  reverseproxy:
      image: manickaa/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: manickaa/backend-api-user
    environment:
      POSTGRES_USERNAME: $POSTGRESS_USERNAME
      POSTGRES_PASSWORD: $POSTGRESS_PASSWORD 
      POSTGRES_DB: $POSTGRESS_DB
      POSTGRES_HOST: $POSTGRESS_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: manickaa/backend-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRESS_USERNAME
      POSTGRES_PASSWORD: $POSTGRESS_PASSWORD 
      POSTGRES_DB: $POSTGRESS_DB
      POSTGRES_HOST: $POSTGRESS_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: $URL
  frontend:
    image: manickaa/frontend-udacity
    ports:
      - "8100:80"